all:
  hosts:
    aws:
      # ansible_ssh_common_args: -i ./keys/aws-key.pem -o StrictHostKeyChecking=no
      ansible_ssh_host: 34.231.49.225
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
