---
- name: Install ansible prerequisites
  hosts: aws

  vars:
    # see https://github.com/geerlingguy/ansible-role-php/issues/226
    php_version: '7.2'
    php_default_version_debian: '7.2'
    php_mysql_package: php7.2-mysql
    
    wordpress_admin_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              62316230383435373066323030396665636364373664366361663465386335373136343065326136
              3261343238353433656264313236366262366436376130650a363739633333616439333961393263
              36646261383639623632316333626235336232666339303133643962386665633930386435646238
              3366346234653431310a343934326439656435626433333235316162623836616264343937333766
              6566
    mysql_dbpassword: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              63356635663736323065376439306331653238336437393861353861333039333132663832316466
              3935646236356435323961613364356435323665313937370a363730303466326261656432313064
              36336231613236663732306530386664366637333935346364393837373638656339323934333465
              6236646434356161360a306665383530303335626633626164653638313461336562636137323563
              3761

    wordpress_owner: www-data
    wp_theme: fluidapp

    backup_folder: backup

  tasks:

  - name: install apache
    tags: apache
    become: true
    import_role: 
      name: geerlingguy.apache
    vars:
      apache_vhosts:
      - servername: "www.aiida.net"
        serveralias: "aiida.net"
        serveradmin: "info@aiida.net"
        documentroot: "/var/www/wp_aiida"
        extra_parameters: |
          # secondary alias
          ServerAlias *.aiida.net
          # block xml-rpc attacks
          <files xmlrpc.php>
            order allow,deny
            deny from all
          </files>

  - name: install php
    tags: php
    become: true
    import_role: 
      name: geerlingguy.php
    vars:
      php_packages_extra:
      - libapache2-mod-php

  - name: install mysql
    tags: mysql
    become: true
    import_role: 
      name: geerlingguy.mysql
    vars:
      mysql_databases:
      - name: aiida_wp2
      mysql_users:
      - name: aiida
        password: "{{ mysql_dbpassword }}"
        priv: "aiida_wp2.*:ALL"

  - name: add php mysql extension
    tags: php
    become: true
    import_role: 
      name: geerlingguy.php-mysql

  - name: install and setup wordpress
    tags: wordpress
    become: true
    import_role: 
      name: oefenweb.wordpress
    vars:
      wordpress_installs:
      - name: wordpress
        dbname: aiida_wp2
        dbuser: aiida
        dbpass: "{{ mysql_dbpassword }}"
        path: /var/www/wp_aiida
        url: http://localhost
        locale: en_US
        title: AiiDA
        admin_name: admin
        admin_email: info@aiida.net
        admin_password: '{{ wordpress_admin_password }}'
        owner: "{{ wordpress_owner }}"
        group: "{{ wordpress_owner }}"
        plugins:
          - name: backwpup
          - name: bwp-recaptcha
            url: http://downloads.wordpress.org/plugin/bwp-recaptcha.zip
          - name: contact-form-7
          - name: disable-comments
            url: https://downloads.wordpress.org/plugin/disable-comments.zip
          - name: display-posts-shortcode
          - name: nextgen-gallery
          - name: wp-custom-post-rss-feed
          - name: sp-news-and-widget
        themes: []
          # - name: "{{ wp_theme }}"
          #   activate: true
        users: {}
        options: []
        queries: []

  - name: write .htaccess file
    # without this none of the page links work!
    tags: wordpress
    become: true
    blockinfile:
      path: /var/www/wp_aiida/.htaccess 
      marker: "# {mark} WordPress"
      owner: "{{ wordpress_owner }}"
      group: "{{ wordpress_owner }}"
      block: |
        <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.php [L]
        </IfModule>

  - name: copy {{ wp_theme }} theme backup
    tags: restore
    copy:
      src: "{{ backup_folder }}/theme-{{ wp_theme }}.zip"
      dest: "/tmp/"

  - name: install {{ wp_theme }} theme backup
    tags: restore
    become: yes
    become_user: "{{ wordpress_owner }}"
    command:
      cmd: "wp-cli --path=/var/www/wp_aiida theme install --activate /tmp/theme-{{ wp_theme }}.zip"
      creates: "/var/www/wp_aiida/wp-content/themes/{{ wp_theme }}"

  - name: copy mysql backup
    tags: restore
    copy:
      src: "{{ backup_folder }}/mysql_table_dump.mysql"
      dest: "/tmp/"
    register: mysql_backup

  - name: import mysql backup
    tags: restore
    when: mysql_backup.changed
    command: wp-cli db import --path=/var/www/wp_aiida /tmp/mysql_table_dump.mysql

  - name: copy other backup files
    tags: restore
    become: yes
    copy:
      src: "{{ backup_folder }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ wordpress_owner }}"
      group: "{{ wordpress_owner }}"
      mode: "755"
    loop:
      - src: dbexample.json
        dest: /var/www/wp_aiida/

  - name: copy other backup (zip) folders
    tags: restore
    become: yes
    copy:
      src: "{{ backup_folder }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ wordpress_owner }}"
      group: "{{ wordpress_owner }}"
      mode: "755"
    loop:
      - src: uploads.zip
        dest: /var/www/wp_aiida/wp-content/uploads
      - src: gallery.zip
        dest: /var/www/wp_aiida/wp-content/gallery
