---
- src: geerlingguy.apache
  version: "3.1.0"
- src: geerlingguy.php
  version: "4.3.1"
- src: geerlingguy.mysql
  version: "3.1.0"
- src: geerlingguy.php-mysql
  version: "2.0.2"
- src: oefenweb.wordpress
  version: v4.6.27
- src: geerlingguy.certbot
  version: "3.1.0"
